name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Run check
      run: cargo run --verbose
    - name: All features build & run check
      run: cargo build --locked --verbose --features all
    - name: Run tests
      run: cargo test --locked --verbose --features all
